{% set name = "expandvars" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/expandvars-{{ version }}.tar.gz
  sha256: 6a0e7821e55ff1ab44f8ca08b50d2b2d01c076a9bc979da940467cb7f105c565

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - expandvars
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sayanarijit/expandvars
  summary: Expand system variables Unix style
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tierriminator
